[package]
name = "process-injection"
version = "0.1.0"
edition = "2021"

[dependencies]
CreateProcessW = "0.1.7"
winapi = { version = "0.3.9", features = ["minwindef", "handleapi", "memoryapi", "processthreadsapi"] }
